### ISSUE TITLE
Solokey (Somu) doesn't get detected by initramfs

### ISSUE THREAD

**Issue by Kabbone** [saravanan30erd/solokey-full-disk-encryption#2]
Hi,
in your vanilla version my Somu doesn't get detected by the initramfs. Some devices need a moment to detect the USB-devices, so one workaround (I am using now) would be including a short sleep in the detection cycle of skfde hook.

**Comment by saravanan30erd** [comment]
Hi @Kabbone 

What is the error you are getting? `SoloKey Not Found` ?

Sure, I will add some delay using sleep. You mentioned that you are using short sleep now, how much time(seconds) are you using?

**Comment by Kabbone** [comment]
yeah, it's `SoloKey Not Found`.
The three loops are finished too fast seemingly. I didn't tinker much with it so far, so I just put a `sleep 3` in there, because I ddin't care too much about the time.
Perhaps a better solution is something like a `sleep 1 or 2` at the end of the failed loop.

**Comment by saravanan30erd** [comment]
@Kabbone added 2 seconds delay before checking for solokey device. Please check it and let me know.

**Comment by Kabbone** [comment]
In my case it get's recognized in the second loop with 2s, in the first with 3s, but second loop is good enough for me.
Thanks!
