### ISSUE TITLE
skfde initramfs hook uses hardcoded LUKS keyslot ID

### ISSUE THREAD

**Issue by HubbeKing** [saravanan30erd/solokey-full-disk-encryption#5]
skfde-enroll allows one to specify which LUKS keyslot to use for the solokey, but the skfde initramfs hook always uses keyslot 3.

If one sets up a root partition to use a keyslot that is not 3 using skfde-enroll, the skfde initramfs hook will always fail to decrypt.

This could probably be solved by just not specifying a keyslot in the initramfs hook, just calling `cryptsetup luksOpen $SKFDE_LUKS_DEV $SKFDE_LUKS_NAME` should result in a successful decryption if the response from the solokey matches ANY of the keyslots.

If not, one could add an SKFDE_LUKS_KEYSLOT setting to skfde.conf that the skfde initramfs hook could use.

**Comment by saravanan30erd** [comment]
Thanks @HubbeKing  I went with option 1 by not using keyslot option in `luksOpen` so solokey response can be matched against any of the keyslots.
