### ISSUE TITLE
[Feature request] Allow skfde initramfs hook to wait for key to be plugged in

### ISSUE THREAD

**Issue by HubbeKing** [saravanan30erd/solokey-full-disk-encryption#6]
It would be nice if the skfde initramfs hook could wait for a solokey to be connected, rather than simply checking 3 times and then failing out.

This is how the ykfde initramfs hook works in the similar `yubikey-full-disk-encryption` project, where there's the additional feature to wait for a configurable number of seconds as well.

Waiting for a key to be connected would make it more convenient to not have the solokey always connected, which is safer - if the solokey is always connected to the system, all an attacker needs in order to decrypt is the solokey PIN, without the solokey attacks become much more difficult.

An ideal solution would be to have a configurable timeout in skfde.conf, but simply waiting endlessly until a key is connected is likely easier to achieve and would likely not disturb anyone already using the hook.

**Comment by saravanan30erd** [comment]
@HubbeKing there is already default timeout 2 seconds for every try,

https://github.com/saravanan30erd/solokey-full-disk-encryption/blob/master/src/hooks/skfde#L16

I can make this one as user configurable in skfde.conf.

**Comment by HubbeKing** [comment]
So long as there's a default value the hook falls back to if there's no value in skfde.conf, that should work just fine :+1:

**Comment by HubbeKing** [comment]
Though it would mean it always waits the full timeout. Would be nicer if it waited only until the key was present... that would likely be a bit trickier, but you could probably just sleep 1, check, then repeat, until the configured timeout has passed or the key is present.

**Comment by saravanan30erd** [comment]
test
